import scala.collection.mutable.Map

object FrequentWords {

	def main(args: Array[String]):Unit = {
		val result = dirtyFreqWords("CAGTTTCTAGATGGGCCCCGAGGGAGATGGGCCTGGTCCTTACCGAGGGCCGAGGGTGGTCCTTACAGTTTCTAGATGGGCCAGATGGGCCCCGAGGGGCGTCGCAAGATGGGCCCCGAGGGTGGTCCTTAAGATGGGCCGCGTCGCATGGTCCTTATGGTCCTTACAGTTTCTTGGTCCTTACAGTTTCTGCGTCGCAAGATGGGCCGCGTCGCACAGTTTCTCAGTTTCTCAGTTTCTCCGAGGGGCGTCGCAAGATGGGCCAGATGGGCCAGATGGGCCAGATGGGCCAGATGGGCCCCGAGGGCAGTTTCTAGATGGGCCTGGTCCTTAAGATGGGCCCAGTTTCTAGATGGGCCGCGTCGCATGGTCCTTATGGTCCTTACAGTTTCTAGATGGGCCCCGAGGGCAGTTTCTTGGTCCTTATGGTCCTTATGGTCCTTATGGTCCTTAAGATGGGCCCCGAGGGGCGTCGCAGCGTCGCATGGTCCTTATGGTCCTTAGCGTCGCAAGATGGGCCCCGAGGGTGGTCCTTAGCGTCGCAGCGTCGCAGCGTCGCATGGTCCTTAGCGTCGCACCGAGGGTGGTCCTTATGGTCCTTATGGTCCTTAGCGTCGCACCGAGGGAGATGGGCCTGGTCCTTAAGATGGGCCTGGTCCTTAAGATGGGCCCAGTTTCTAGATGGGCCGCGTCGCACAGTTTCTTGGTCCTTAAGATGGGCCTGGTCCTTAGCGTCGCACAGTTTCTAGATGGGCCCAGTTTCTCAGTTTCTCCGAGGGTGGTCCTTATGGTCCTTAAGATGGGCCCCGAGGGTGGTCCTTAGCGTCGCAGCGTCGCAGCGTCGCACAGTTTCTTGGTCCTTACAGTTTCTGCGTCGCA", 14)

		println(result)
	}

	def dirtyFreqWords(text: String, k: Int):Map[String, Int] = {

		var ms = scala.collection.mutable.Map[String,Int]()
		@annotation.tailrec
		def go(index: Int):Map[String, Int] = {
			if(ms contains text.substring(index, index+k)) {
				ms(text.substring(index, index+k)) += 1
			}
			else ms +=(text.substring(index, index+k) -> 1)

			if(index < (text.length - k)) go(index + 1) else ms

		}
		
		go(0)


	}
}