/*
* This program counts the number of occurances of a substring of a given string
* author: John Devivo
* Date: 10/18/14
*/

object PatternCount {
	
	def main(args: Array[String]):Unit = {
		val result = patCount("TCGGATAAGTCGGATATCTTCTCGGATATAGATTCGGATAGCTCTCGGATAATCGGATAGTCGGATAAGTCGGATATTCGGATATCAATCGGATATCTCTCGGATATTCGGATACGAGTCTCGGATATGCTTCGGATATCGGATAGTCGGATATCGGATAGTAGTTCGGATATATCGGATATCGGATATTCGGATATCGGATATCGGATAGTGTCGGATAAATCGGATACTCGGATAGTTGGCTCGGATACATTCGGATATCCCCTGATTGGTCGGATAATCGGATATGTCGGATATCGGATATCGGATAGTCGGATAAATGCGTCGGATACTCGGATATCGGATACTGCATCGGATACGGCTTCGGATAGGACAATTCGGATATCGGATAAATCGGATATCGTTCGGATAGATCGGATAGGGAAATCGGATAAATCGCCCTGTTCGGATATTCGGATAGTAAAAGATCGGATATCGGCGACCTCGGATATGATGCGTACTCATTCGGATATCGGATAGCCGTATCGGATATCGGATACGAAGTCGGATATGATCTCGGATAATTCGGATACACAAGGGTGCGAGCGTCGGATACTTCTCGGATAGTCGGATACTTTTTCGGATACGCTCGGATACGTCGGATACATCGGATATCGGATATCGGATAGTCGGGCCACTCGGATATTCTAGGTCGGATACCTCGGATAGATTTCGGATACTCGGATATCGGATATCGGATACTCGGATAGGTCGGATATATCGGATAGATGTGAATCGGATAATCGGATATCGGATAAAGACATCGGATATTCGGATACTAGCTGTGGTCGGATACCGTCGGATACGGCTTGTTCGGATATCGGATAAGTCGGATATCGGATAGTCGGATAAGGTCGGATATTCGGATATTCGGATATATAACGCCGTCGGATACTCGGATAATCGGATAAGTCGGATATCGGATATTCGGATA", "TCGGATATC")
		println(result)
	}

	def patCount(text: String, pattern: String): Int = {

		def go(count: Int, index: Int):Int = {

			if(pattern == text.substring(index, (index+pattern.length()))) {

				if((1 + index) <= (text.length() - pattern.length())) {
					go(count + 1, index + 1)
				}
				else count + 1

			}

			else {
				if((1 + index) <= (text.length() - pattern.length())) {
					go(count, index + 1)
				}
				else count
			}
				
		}

		go(0, 0)
	}

}