/*
* This program counts the number of occurances of a substring of a given string
* author: John Devivo
* Date: 10/18/14
*/

import scala.collection.immutable.StringLike

object PatternCount {
	
	def main(args: Array[String]):Unit = {
		val result = patCount("TCGGATAAGTCGGATATCTTCTCGGATATAGATTCGGATAGCTCTCGGATAATCGGATAGTCGGATAAGTCGGATATTCGGATATCAATCGGATATCTCTCGGATATTCGGATACGAGTCTCGGATATGCTTCGGATATCGGATAGTCGGATATCGGATAGTAGTTCGGATATATCGGATATCGGATATTCGGATATCGGATATCGGATAGTGTCGGATAAATCGGATACTCGGATAGTTGGCTCGGATACATTCGGATATCCCCTGATTGGTCGGATAATCGGATATGTCGGATATCGGATATCGGATAGTCGGATAAATGCGTCGGATACTCGGATATCGGATACTGCATCGGATACGGCTTCGGATAGGACAATTCGGATATCGGATAAATCGGATATCGTTCGGATAGATCGGATAGGGAAATCGGATAAATCGCCCTGTTCGGATATTCGGATAGTAAAAGATCGGATATCGGCGACCTCGGATATGATGCGTACTCATTCGGATATCGGATAGCCGTATCGGATATCGGATACGAAGTCGGATATGATCTCGGATAATTCGGATACACAAGGGTGCGAGCGTCGGATACTTCTCGGATAGTCGGATACTTTTTCGGATACGCTCGGATACGTCGGATACATCGGATATCGGATATCGGATAGTCGGGCCACTCGGATATTCTAGGTCGGATACCTCGGATAGATTTCGGATACTCGGATATCGGATATCGGATACTCGGATAGGTCGGATATATCGGATAGATGTGAATCGGATAATCGGATATCGGATAAAGACATCGGATATTCGGATACTAGCTGTGGTCGGATACCGTCGGATACGGCTTGTTCGGATATCGGATAAGTCGGATATCGGATAGTCGGATAAGGTCGGATATTCGGATATTCGGATATATAACGCCGTCGGATACTCGGATAATCGGATAAGTCGGATATCGGATATTCGGATA", "TCGGATATC")
		println(result)
	}

	def patCount(text: String, pattern: String):Int = {

		@annotation.tailrec
		def go(s: String, count: Int):Int = {
			if(s.length < pattern.length) count 
			else {
				if(s.startsWith(pattern)) go(s.tail, count + 1) else go(s.tail, count)
			}
		}

		go(text, 0)
	}

}